---
title: "Events"
# subtitle: "A List of Classes by Semester/Year"
date-modified: last-modified
title-block-banner: images/banner_event.jpg
---

## 사회(지리)과 예비교사를 위한 AIㆍ디지털 역량강화 워크숍

### 프로그램의 목표

본 워크숍은 사범대학 재학 중인 중등 사회과(지리) 예비 교원들의 AI·디지털 역량을 실질적으로 함양하는 것을 목적으로 한다. 이를 위해 온라인 저작도구 쿼토(Quarto)와 오픈소스 프로그래밍 언어 R을 학습한다. 궁극적으로 전통적인 교수-학습 자료를 넘어 현장에서 적용 가능한 인터랙티브 교수-학습 자료를 제작하는 역량을 기르고자 한다.

### 프로그램의 개요

-   사회(지리) 교과 예비 교원이 교육 현장에서 활용할 수 있는 AI 디지털 기술을 습득하고 이를 기반으로 자신만의 교수-학습 도구를 개발하고 할용하는 역량을 기르는 것을 목적으로 함.

-   교육프로그램은 사전 학습 5시간과 본학습 15시간으로 구성됨.

-   사전학습을 통해 기초적인 프로그래밍 지식을 습득하고, 본 수업에서 이를 활용하여 교수-학습 도구를 개발하는 실습이 이루어짐.

-   사회과(지리) 예비교원이 유용하게 활용할 수 있는 디지털 지리공간기술, 오픈 API, 자연어 처리, 텍스트 마이닝, 데이터 탐색 및 머신러닝, 지리공간적 시각화, 디지털 대시보드 등에 대한 개념 강의 및 실습을 중심으로 이루어짐.

-   최종적으로 프로그래밍을 활용해 사회과 수업에서 활용할 수 있는 인터랙티브 교수-학습 자료를 개발하고, 이를 활용한 수업을 설계하는 과제를 부여함.

### 일시 및 장소

-   2024년 8월 5일(월) \~ 9일(금) 오후 2\~5시 총 5일(저녁식사 제공)

-   10동 103호

### 참가 혜택

-   사회(지리) 교과 예비교사에게 필요한 AIㆍ디지털 역량 습득 및 관련 수업 설계 경험 획득

-   프로그램 수료증 발급(출석율 90% 이상 이수시)

-   학업장려금 15만원 지급(출석률 90% 이상 이수시)

### 프로그램 내용

+----------+--------------------------+---------------------------------------------------------------------------+----------------------------------------+
| 차시     | 교육 시간                | 교육 내용                                                                 | 강사 및 실습 조교                      |
+==========+==========================+===========================================================================+========================================+
| 사전학습 | 온라인 강의(3시간)       | -   주제: 사회과 수업에서 활용 가능한 AI 및 디지털 도구 소개              | 이상일(서울대학교 지리교육과 교수)     |
|          |                          |                                                                           |                                        |
|          |                          |     -   구성: 녹화 영상 3편(이론 1편, 실습 2편), 총 5시간                 | 김세창(서울대학교 지리교육과 석사)     |
|          |                          |                                                                           |                                        |
|          |                          | -   이론: 세 가지 사이언스(약 1시간)                                      | 김우형(서울대학교 지리교육과 석사과정) |
|          |                          |                                                                           |                                        |
|          |                          | -   실습                                                                  |                                        |
|          |                          |                                                                           |                                        |
|          |                          |     -   실습 1: 최신 지리공간기술로서의 구글 어스 스튜디오(약 2시간)      |                                        |
|          |                          |                                                                           |                                        |
|          |                          |     -   실습 2: R을 통한 데이터사이언스 프로세스(약 2시간)                |                                        |
+----------+--------------------------+---------------------------------------------------------------------------+----------------------------------------+
| Day 1    | 8월 5일(월) 14:00\~17:00 | -   주제: AIㆍ디지털 역량과 사회 교과                                     | 이상일(서울대학교 지리교육과 교수)     |
|          |                          |                                                                           |                                        |
|          |                          | -   강의 내용                                                             | 김세창(서울대학교 지리교육과 석사)     |
|          |                          |                                                                           |                                        |
|          |                          |     -   AIㆍ디지털 사회의 도래와 사회 교과                                | 김우형(서울대학교 지리교육과 석사과정) |
|          |                          |                                                                           |                                        |
|          |                          |     -   AIㆍ디지털 커뮤니케이션 역량과 도구                               |                                        |
|          |                          |                                                                           |                                        |
|          |                          | -   실습 내용                                                             |                                        |
|          |                          |                                                                           |                                        |
|          |                          |     -   AIㆍ디지털 커뮤니케이션 도구로서의 Quarto 입문                    |                                        |
|          |                          |                                                                           |                                        |
|          |                          |     -   Quarto를 활용한 대시보드 만들기                                   |                                        |
+----------+--------------------------+---------------------------------------------------------------------------+----------------------------------------+
| Day 2    | 8월 6일(화) 14:00\~17:00 | -   주제: 데이터의 수집 및 정련화                                         | 이상일(서울대학교 지리교육과 교수)     |
|          |                          |                                                                           |                                        |
|          |                          | -   강의 내용                                                             | 김세창(서울대학교 지리교육과 석사)     |
|          |                          |                                                                           |                                        |
|          |                          |     -   데이터의 수집 방법(웹스크레이핑과 오픈 API 활용)                  | 김우형(서울대학교 지리교육과 석사과정) |
|          |                          |                                                                           |                                        |
|          |                          |     -   정돈된 데이터의 개념                                              |                                        |
|          |                          |                                                                           |                                        |
|          |                          |     -   문제의 현황 파악                                                  |                                        |
|          |                          |                                                                           |                                        |
|          |                          | -   실습 내용                                                             |                                        |
|          |                          |                                                                           |                                        |
|          |                          |     -   R을 활용한 오픈 API 기반 데이터 수집                              |                                        |
|          |                          |                                                                           |                                        |
|          |                          |     -   R을 활용한 데이터 불러오기 및 정리하기                            |                                        |
+----------+--------------------------+---------------------------------------------------------------------------+----------------------------------------+
| Day 3    | 8월 7일(수) 14:00\~17:00 | -   주제: 탐색적 데이터 분석                                              | 이상일(서울대학교 지리교육과 교수)     |
|          |                          |                                                                           |                                        |
|          |                          | -   강의 내용                                                             | 김세창(서울대학교 지리교육과 석사)     |
|          |                          |                                                                           |                                        |
|          |                          |     -   탐색적 데이터 분석의 원리와 절차                                  | 김우형(서울대학교 지리교육과 석사과정) |
|          |                          |                                                                           |                                        |
|          |                          |     -   데이터 시각화의 개념과 기법                                       |                                        |
|          |                          |                                                                           |                                        |
|          |                          |     -   문제의 이해 및 수업 소재 선정                                     |                                        |
|          |                          |                                                                           |                                        |
|          |                          | -   실습 내용                                                             |                                        |
|          |                          |                                                                           |                                        |
|          |                          |     -   R을 활용한 데이터의 변형 및 시각화                                |                                        |
|          |                          |     -   R을 활용한 탐색적 데이터 분석                                     |                                        |
+----------+--------------------------+---------------------------------------------------------------------------+----------------------------------------+
| Day 4    | 8월 8일(목) 14:00\~17:00 | -   주제: 고급 시각화와 디지털 교수-학습 대시보드의 설계                  | 이상일(서울대학교 지리교육과 교수)     |
|          |                          |                                                                           |                                        |
|          |                          | -   강의 내용                                                             | 김세창(서울대학교 지리교육과 석사)     |
|          |                          |                                                                           |                                        |
|          |                          |     -   인트렉티브 시각화의 종류                                          | 김우형(서울대학교 지리교육과 석사과정) |
|          |                          |                                                                           |                                        |
|          |                          |     -   지리공간적 시각화의 개념과 기법                                   |                                        |
|          |                          |                                                                           |                                        |
|          |                          |     -   탐구 수업을 위한 디지털 대시보드의 설계                           |                                        |
|          |                          |                                                                           |                                        |
|          |                          | -   실습 내용                                                             |                                        |
|          |                          |                                                                           |                                        |
|          |                          |     -   R을 활용한 인트렉티브 및 지리공간적 시각화                        |                                        |
|          |                          |                                                                           |                                        |
|          |                          |     -   Quarto를 활용한 대시보드의 설계                                   |                                        |
+----------+--------------------------+---------------------------------------------------------------------------+----------------------------------------+
| Day 5    | 8월 9일(금) 14:00\~17:00 | -   주제: 고급 인트렉티브 기능과 디지털 교수-학습 대시보드의 제작 및 공유 | 이상일(서울대학교 지리교육과 교수)     |
|          |                          |                                                                           |                                        |
|          |                          | -   강의 내용                                                             | 김세창(서울대학교 지리교육과 석사)     |
|          |                          |                                                                           |                                        |
|          |                          |     -   고급 인트렉티브 기능                                              | 김우형(서울대학교 지리교육과 석사과정) |
|          |                          |                                                                           |                                        |
|          |                          |     -   탐구 수업을 위한 디지털 대시보드의 제작                           |                                        |
|          |                          |                                                                           |                                        |
|          |                          |     -   웹 배포를 통한 공유                                               |                                        |
|          |                          |                                                                           |                                        |
|          |                          | -   실습 내용                                                             |                                        |
|          |                          |                                                                           |                                        |
|          |                          |     -   Quarto를 활용한 대시보드의 제작                                   |                                        |
|          |                          |     -   Quarto Pub을 통한 웹 배포                                         |                                        |
+----------+--------------------------+---------------------------------------------------------------------------+----------------------------------------+

### 사전 학습(동영상)

-   YouTube 채널: [AI·디지털 기반 사회과 교육 워크샵](https://www.youtube.com/@AIEDAP-social-studies)

-   내용 구성

    -   세 가지 사이언스의 융합(강의): [링크](https://www.youtube.com/watch?v=pVLhGhniMjg&list=PLBhmlKluaonqAygapYjjTQD2YzC8N5CBj&index=5)

    -   구글 어스 스튜디오(실습): [링크](https://www.youtube.com/watch?v=Z3KlpPhS7hc&list=PLBhmlKluaonqAygapYjjTQD2YzC8N5CBj&index=1)

    -   R과 Quarto(실습)

        -   [링크](https://www.youtube.com/watch?v=JCxr_ThIg6A&list=PLBhmlKluaonqAygapYjjTQD2YzC8N5CBj&index=2)

        -   [링크](https://www.youtube.com/watch?v=sOkGRQbOWh0&list=PLBhmlKluaonqAygapYjjTQD2YzC8N5CBj&index=3)

        -   [링크](https://www.youtube.com/watch?v=Xy5BHPXrqlg&list=PLBhmlKluaonqAygapYjjTQD2YzC8N5CBj&index=4)

### 학습 자료

#### Day 1(8월 5일)

-   강의 자료

-   실습 자료

#### Day 2(8월 6일)

-   강의 자료

-   실습 자료

#### Day 3(8월 7일)

-   강의 자료

-   실습 자료

#### Day 4(8월 8일)

-   강의 자료

-   실습 자료

#### Day 5(8월 9일)

-   강의 자료

-   실습 자료

### 참고문헌

#### 데이터사이언스와 R

-   Wickham, Hadley, Mine Çetinkaya-Rundel, and Garrett Grolemund, 2023, [*R for Data Science: Import, Tidy, Transform, Visualize, and Model Data*](https://r4ds.hadley.nz/)*,* 2nd edition, Boston: O’Reilly. 

-   Bonnell, Jerry, and Mitsunori Ogihara. 2023. [*Exploring Data Science with R and the Tidyverse*](https://ds4world.cs.miami.edu/). 1st edition. Chapman; Hall/CRC.

-   Irizarry, Rafael A. 2024. [*Introduction to Data Science: Data Wrangling and Visualization with R*](https://rafalab.dfci.harvard.edu/dsbook-part-1/). 2nd edition, Boca Raton: CRC Press.

-   한국알사용자회, [데이터 과학을 지탱하는 기본기](https://r2bit.com/book_analytics/), 웹북

-   김기환, 2023, [R 프로그래밍(개정판)](https://kilhwan.github.io/rprogramming/), 웹북

#### 쿼토 Quarto

-   [Quarto 웹사이트](https://quarto.org/)

-   한국알사용자회ㆍ이광춘, 2024, [챗GPT쿼토: 인공지능 시대 과학기술 저작 도구](https://r2bit.com/gpt-quarto/), 웹북

#### 샤이니 Shiny

-   [Shiny 웹사이트](https://shiny.posit.co/)

-   Wickham, Hadley, 2021, [*Mastering Shiny: Build Interactive Apps, Reports, and Dashboards Power by R*](https://mastering-shiny.org/)*,* Sebastopol, CA: O’REILLY. (이영록 옮김, 2022, [R 사용자를 위한 Shiny 마스터 가이드](https://www.yes24.com/Product/Goods/116598818), 서울: 인사이트.)

-   Granjon, David, 2022, [*Outstanding User Interfaces with Shiny*](https://unleash-shiny.rinterface.com/), Boaca Raton: CRC Press.

-   Fay, Colin, Vincent Guyader, Sebastien Rochette, and Cervan Girard. 2022, [*Engineering Production-Grade Shiny Apps*](https://engineering-shiny.org/), Boca Raton: CRC Press.

#### 시각화

-   Wickham, Hadley. 2016. [*ggplot2: Elegant Graphics for Data Analysis*](https://ggplot2-book.org/). 2nd edition, Switzerland: Springer. (박진수 옮김, 2017. [R로 분석한 데이터를 멋진 그래픽으로 ggplot2](https://www.yes24.com/Product/Goods/57248968). 부천: 프리렉.)

-   Kabacoff, Robert, 2024, [*Modern Data Visualization with R*](https://rkabacoff.github.io/datavis/), Boca Raton: CRC Press.

-   한국알사용자회, [데이터 시각화](https://r2bit.com/book_viz/), 웹북
