---
title: "Classes"
subtitle: "A List of Classes by Semester/Year"
date-modified: last-modified
title-block-banner: images/banner_lectures_new.jpg
---

## Spring Semester in 2025

### Introduction to Population Geography <br />인구지리학개론

-   Course code: 713.226A
-   Undergraduate, offered by [Department of Geography Education](https://geoedu.snu.ac.kr/)
-   Instructor: [Sang-Il Lee](https://sangillee66.github.io/) (Professor in Seoul National University)
    -   [si_lee\@snu.ac.kr](mailto:%20si_lee@snu.ac.kr), 02-880-9028, 10-319
-   TA: Hyemin Jeon
-   Place: 10-102
-   Time: 10:30 - 11:45, Mondays & Wednesdays

### Remote Sensing and Geographic Data Analysis <br />원격탐사와 지리자료분석

-   Course code: 713.431
-   Undergraduate, offered by [Department of Geography Education](https://geoedu.snu.ac.kr/)
-   Instructor: [Sang-Il Lee](https://sangillee66.github.io/) (Professor in Seoul National University)
    -   [si_lee\@snu.ac.kr](mailto:%20si_lee@snu.ac.kr), 02-880-9028, 10-319
-   TA: Hyemin Jeon
-   Place: 10-102
-   Time: 14:00 - 17:00, Fridays

### Spatial Data Analysis and Geography Education <br />공간데이터분석과 지리교육

-   Course code: 713.641A
-   Graduate, offered by [Department of Geography Education](https://geoedu.snu.ac.kr/)
-   Instructor: [Sang-Il Lee](https://sangillee66.github.io/) (Professor in Seoul National University)
    -   [si_lee\@snu.ac.kr](mailto:%20si_lee@snu.ac.kr), 02-880-9028, 10-319
-   TA: Hyemin Jeon
-   Place: 10-102
-   Time: 18:00 - 21:00, Thursdays

### AI Era and Core Competence Education <br />인공지능 시대와 핵심역량 교육

-   Course code: M3450.000200
-   Graduate, offered by [Department of AI-Integrated Education](https://aied.snu.ac.kr/) (AI융합교육학과)
-   Team Teaching
    -   Data Science and AI/Digital Competencies for Human and Social Subjects (데이터사이언스와 인문사회 AIㆍ디지털 역량)
-   Instructor: [Sang-Il Lee](https://sangillee66.github.io/) (Professor in Seoul National University)
    -   [si_lee\@snu.ac.kr](mailto:%20si_lee@snu.ac.kr), 02-880-9028, 10-319
-   TA: Hyemin Jeon
-   Place: 10-1-103
-   Time: 18:30 - 21:30, April 18, 25 & May 2

## Autumn Semester in 2024

### Geographic Information Systems and Geography Education <br />지리정보체계와 지리교육

-   Course code: 700.432
-   Undergraduate, offered by [Department of Geography Education](https://geoedu.snu.ac.kr/)
-   Instructor: [Sang-Il Lee](https://sangillee66.github.io/) (Professor in Seoul National University)
    -   [si_lee\@snu.ac.kr](mailto:%20si_lee@snu.ac.kr), 02-880-9028, 10-319
-   TA: Woohyung Kim
-   Place: 10-102
-   Time: 10:30 - 11:45, Mondays & Wednesdays

### Topics in Spatial Data Science: Spatial Modelling with Machine Learning <br />공간데이터사이언스 특강: 머신러닝을 활용한 공간 모델링

-   Course code: M1862.000700
-   Graduate, offered by [Department of Geography Education](https://geoedu.snu.ac.kr/)
-   Instructor: [Sang-Il Lee](https://sangillee66.github.io/) (Professor in Seoul National University)
    -   [si_lee\@snu.ac.kr](mailto:%20si_lee@snu.ac.kr), 02-880-9028, 10-319
-   TA: Woohyung Kim
-   Place: 10-102
-   Time: 18:00 - 20:50, Thursdays

## Spring Semester in 2024

### Cartography <br />지도학

-   Course code: 700.231
-   Undergraduate, offered by [Department of Geography Education](https://geoedu.snu.ac.kr/)
-   Instructor: [Sang-Il Lee](https://sangillee66.github.io/) (Professor in Seoul National University)
    -   [si_lee\@snu.ac.kr](mailto:%20si_lee@snu.ac.kr), 02-880-9028, 10-319
-   TA: Woohyung Kim
-   Place: 10-1-107
-   Time: 11:00 - 12:15, Mondays & Wednesdays
-   [Syllabus](classes/2024_1_Cartography.qmd)

### Topics in Cartography and Cartography Education: Maps and Civilization <br />지도학 및 지도교육 특강: 지도와 문명

-   Course code: M1862.000400
-   Graduate, offered by [Department of Geography Education](https://geoedu.snu.ac.kr/)
-   Instructor: [Sang-Il Lee](https://sangillee66.github.io/) (Professor in Seoul National University)
    -   [si_lee\@snu.ac.kr](mailto:%20si_lee@snu.ac.kr), 02-880-9028, 10-319
-   TA: TBD
-   Place: TBD
-   Time: 18:00 - 20:50, Thursdays
-   [Syllabus](classes/2024_1_Topics_Carto.qmd)

### Designing Human and Social Education Contents for AI Convergence Education <br />AI 융합교육을 위한 인문사회 컨텐츠 설계

-   Course code: M3450.001400
-   Graduate, offered by [Department of AI-Integrated Education](https://aied.snu.ac.kr/) (AI융합교육학과)
-   Instructor: [Sang-Il Lee](https://sangillee66.github.io/) (Professor in Seoul National University)
    -   [si_lee\@snu.ac.kr](mailto:%20si_lee@snu.ac.kr), 02-880-9028, 10-319
-   TA: Sechang Kim and Woohyung Kim
-   Place: 10-207
-   Time: 18:30 - 21:20, Tuesdays
-   [Syllabus](classes/2024_1_AI_Edu.qmd)
