---
title: "Publications"
subtitle: "Books and Papers"
date-modified: last-modified
title-block-banner: images/banner_works_new.jpg
# bibliography: references.bib
---

## Books

-   정대홍 외 20인, 2022, [인공지능 시대 교사가 만드는 미래학교](http://www.kyoyookbook.co.kr/shop/item.php?it_id=1661472925), 교육과학사, 파주.

-   이상일ㆍ손일 옮김, 2021, [지도와 거짓말](http://www.purungil.co.kr/books/books_show.php?seq=617&mode=category&category_seq=_1_), 서울: 푸른길. (Monmonier, Mark S, 2018, [*How to Lie with Maps*](https://press.uchicago.edu/ucp/books/book/chicago/H/bo27400568.html)*,* Third edition, Chicago, IL: The University of Chicago Press.)

-   이건학ㆍ김감영ㆍ김영호ㆍ김영훈ㆍ신정엽ㆍ이상일 옮김, 2014, [지도학과 지리적 시각화](http://www.sigmapress.co.kr/shop/m_mall_detail.php?ps_ctid=01130000&ps_goid=1873&depth_2_display=none), 서울: 시그마프레스. (Slocum, Terry A., Robert B. McMaster, Fritz C. Kessler, and Hugh H. Howard. 2009, [*Thematic Cartography and Geovisualization*](https://www.amazon.com/Thematic-Cartography-Geovisualization-Terry-Slocum/dp/0132298341), 3rd ed., Upper Saddle River, NJ: Pearson Prentice Hall.)

-   이상일 옮김, 2014, [지구 끝까지: 세상을 바꾼 100장의 지도](http://www.purungil.co.kr/books/books_show.php?seq=259&mode=category&category_seq=), 서울: 푸른길. (Harwood, Jeremy, 2011, [*To the Ends of the Earth: 100 Maps that Changed the World*](https://www.amazon.com/Ends-Earth-Maps-Changed-World/dp/0785828982), New York, N.Y.: Chartwell Books.)

-   이상일ㆍ김현미ㆍ조대헌 옮김, 2013, [짧은 지리학 개론 시리즈: GIS](http://www.sigmapress.co.kr/shop/m_mall_detail.php?ps_ctid=01130000&ps_goid=1878&depth_2_display=none), 서울: 시그마프레스. (Schuurman, Nadine, 2004, [*GIS: A Short Introduction*](https://blackwells.co.uk/bookshop/product/GIS-by-Nadine-Schuurman/9780631235330), Malden, MA: Blackwell.)

-   신정엽ㆍ이건학ㆍ김감영ㆍ전용완ㆍ이상일ㆍ조대헌ㆍ최은영ㆍ김현미ㆍ홍일영 옮김, 2011, [도시의 탐색: 도시공간이론과 GIS를 활용한 공간분석](http://www.sigmapress.co.kr/shop/m_mall_detail.php?ps_ctid=01130000&ps_goid=1888&depth_2_display=none), 서울: 시그마프레스, 서울. (Greene, Richard P., and James B. Pick, 2006, [*Exploring the Urban Community: A GIS Approach*](https://www.amazon.com/Exploring-Urban-Community-GIS-Approach/dp/0130175765/ref=sr_1_1?dib=eyJ2IjoiMSJ9.vZnc6WsGAk5LuI2Ebz1oAg.pAsPg8tfRznJTlpv9I35rWby2rNjm-Shv80TwmEyA8A&dib_tag=se&keywords=9780130175762&linkCode=qs&qid=1705647278&s=books&sr=1-1), Upper Saddle River, NJ: Prentice Hall.)

-   이상일ㆍ신정엽ㆍ김현미ㆍ홍일영ㆍ김감영ㆍ전용완ㆍ조대헌ㆍ김종근ㆍ이건학 옮김, 2009, [지리정보시스템과 지리정보과학](http://www.sigmapress.co.kr/shop/m_mall_detail.php?ps_ctid=01130000&ps_goid=1895&depth_2_display=none), 서울: 시그마프레스. (Longley, Paul A., Michael F. Goodchild, David J. Maguire, and David W. Rhind, 2008, [*Geographical Information Systems and Science*](https://www.amazon.com/Geographic-Information-Systems-Science-Longley/dp/0470870001/ref=sr_1_4?crid=3I52LW8W5RTUH&dib=eyJ2IjoiMSJ9.ltOuoubUFKLqbIheQHxZt-TyzjyTL2GvTJkA-04mBm03zhqTvOZ8FABiWj9qbdwiCRwhYBUFjbG0pDfdbSQlvn81PiftMJcao1e4FqeVR6eog3b3qaKLR3JF_QpEfdZpN-HR6-Eu3wizMe0kOsZAR39-VBjBTVr5LGp6SbpdVDBst9U4rgdKeIuAfRRuQMy5tq2AcfUg6Go0o5vEJ5vqp6rXnS5nezxoU2X_QoM8Hbs.v2B3uuNCymQs7C0QrJk34_uck0u9J_dDLe5IQ2OPCWI&dib_tag=se&keywords=Geographical+Information+Systems+and+Science+goodchild&qid=1705647466&s=books&sprefix=geographical+information+systems+and+science+goodchil%2Cstripbooks-intl-ship%2C239&sr=1-4)*,* 2nd. ed., reprinted, Chichester: Wiley.)

-   신정엽ㆍ이상일, 2008, [GIS의 개념과 원리](https://snu-primo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?vid=82SNU&search_scope=ALL&docid=82SNU_INST21479053960002591&lang=ko_KR), 서울: 다락방.

## Papers

> Click on [{{< bi file-pdf-fill size=1.5rem >}}](https://get.adobe.com/reader/) to download each paper.

### 2024

-   이상일ㆍ고보경ㆍ고준보ㆍ김세창ㆍ김우형ㆍ임철일, 2025, “사회과 예비 교원의 디지털 역량 향상을 위한 프로그래밍 기반 교육프로그램 개발,” 교육공학연구, 41(1), 80-109. <http://dx.doi.org/10.17232/KSET.41.1.79>. [{{< bi file-pdf-fill >}}](papers/2025_03_이상일_고보경_고준보_김세창_김우형_임철일.pdf)

-   이상일ㆍ이소영ㆍ김세창, 2024, "우리나라의 연령-특수적 인구이동 편향성에 대한 다중스케일 분석," 대한지리학회지, 59(5), 656-672. <https://doi.org/10.22776/kgs.2024.59.5.656>. [{{< bi file-pdf-fill >}}](papers/2024_02_대한지리학회지_이상일_이소영_김세창.pdf)

-   이상일ㆍ조대헌. 2024. “우리나라 인구이동 데이터의 다양성과 상호보완성에 관한 연구 - 주민등록과 등록센서스 데이터의 비교를 중심으로 -.” 대한지리학회지, 59(4), 487-504. <https://doi.org/10.22776/kgs.2024.59.4.487>. [{{< bi file-pdf-fill >}}](papers/2024_01_대한지리학회지_이상일_조대헌.pdf)

### 2023

-   이상일ㆍ이소영, 2023, “인구이동이 인구재분포에 미치는 영향력의 시공간적 역동성 탐색: 우리나라 국내 인구이동에의 적용,” 한국지도학회지, 23(1), 1–19. <https://doi.org/10.16879/jkca.2023.23.1.001>. [{{< bi file-pdf-fill >}}](papers/2023_03_한국지도학회지_이상일_이소영.pdf)

-   이소영ㆍ이상일ㆍ김세창, 2023, "AI 의 교육적 활용에 대한 중등 사회과 교사의 인식 및 연수 수요 분석,” 학습자중심교과교육연구, 23(7), 743–759. <https://doi.org/10.22251/jlcci.2023.23.7.743>. [{{< bi file-pdf-fill >}}](papers/2023_02_학습자중심교과교육연구_이소영_이상일_김세창.pdf)

-   이소영ㆍ이상일ㆍ박의현ㆍ최학모, 2023. “사회과 챗봇의 설계와 교육적 활용 방안에 관한 연구 - 중학교 지리 영역을 중심으로,” 한국지리환경교육학회, 31(1), 147–163. <https://doi.org/10.17279/jkagee.2023.31.1.147>. [{{< bi file-pdf-fill >}}](papers/2023_01_한국지리환경교육학회지_이소영_이상일_박의현_최학모.pdf)

### 2022

-   조대헌ㆍ이상일, 2022, “우리나라 소지역 인구추계를 위한 방법론 비교 분석,” 한국지도학회지, 22(2), 51–67. <https://doi.org/10.16879/jkca.2022.22.2.051>. [{{< bi file-pdf-fill >}}](papers/2022_03_한국지도학회지_조대헌_이상일.pdf)

-   이상일ㆍ김현미, 2022, “우리나라 대도시의 연령-특수적 전출입 플로 분석: 2020 년 인구이동을 사례로,” 한국지도학회지, 22(2), 1–16. <https://doi.org/10.16879/jkca.2022.22.2.001>. [{{< bi file-pdf-fill >}}](papers/2022_02_한국지도학회지_이상일_김현미.pdf)

-   김민성ㆍ이상일, 2022, “인공지능의 교육적 활용과 지리 교수학습 전략,” 정대홍 등 저, 인공지능 시대, 교사가 만드는 미래학교, 교육과학사, 105–127. [{{< bi file-pdf-fill >}}](papers/2022_01_인공지능_김민성_이상일.pdf)

### 2021

-   이상일ㆍ이소영, 2021, “인구이동 플로의 지리적 시각화를 위한 개념적 명료화: 우리나라 2020년 인구이동에 대한 주제도 제작,” 한국지도학회지, 21(3), 23–42. <https://doi.org/10.16879/jkca.2021.21.3.023>. [{{< bi file-pdf-fill >}}](papers/2021_04_한국지도학회지_이상일_이소영.pdf)

-   이상일ㆍ김현미, 2021, “인구이동 플로의 연령-특수적 패턴 분석을 위한 방법론 연구-우리나라 시군구 단위 인구이동에의 적용,” 대한지리학회지, 56(5), 537–550. <https://doi.org/10.22776/kgs.2021.56.5.537>. [{{< bi file-pdf-fill >}}](papers/2021_03_대한지리학회지_이상일_김현미.pdf)

-   김현미ㆍ이상일, 2021, “이성분트렌드매핑 기법을 이용한 우리나라 인구 변화의 시공간적 역동성 시각화,” 한국사진지리학회지, 31(3), 51–68. <https://doi.org/10.35149/jakpg.2021.31.3.004>. [{{< bi file-pdf-fill >}}](papers/2021_02_한국사진지리학회지_김현미_이상일.pdf)

-   김현미ㆍ이상일, 2021, “우리나라 디지털 행정구역 경계 파일의 일반화에 관한 연구: 주제도 제작용 기본도를 중심으로,” 한국지도학회지, 21(2), 29–44. <https://doi.org/10.16879/jkca.2021.21.2.029>. [{{< bi file-pdf-fill >}}](papers/2021_01_한국지도학회지_김현미_이상일.pdf)

### 2020

-   이상일ㆍ조대헌, 2020, “우리나라 소지역 인구 추계를 위한 방법론 연구: 추세외삽법을 중심으로,” 지리교육논집, 64, 1–19. [I410-ECN-0102-2023-300-000521029](https://kiss.kstudy.com/Detail/Ar?key=3935192). [{{< bi file-pdf-fill >}}](papers/2020_03_지리교육논집_이상일_조대헌.pdf)

-   이상일ㆍ이몽현, 2020, “무작위합역 절차의 다양성에 대한 시뮬레이션 연구,” 한국지도학회지, 20(3), 93–107. <https://doi.org/10.16879/jkca.2020.20.3.093>. [{{< bi file-pdf-fill >}}](papers/2020_02_한국지도학회지_이상일_이몽현.pdf)

-   Lee, Sang-Il, 2020, “Neighborhood effects,” In Kobayashi, A., ed., *International Encyclopedia of Human Geography*, 2nd edition, Volume 9, Oxford: Elsevier, 335–339. <https://doi.org/10.1016/B978-0-08-102295-5.10409-3>. [{{< bi file-pdf-fill >}}](papers/2020_01_IEHG_Lee.pdf)

### 2019

-   이상일ㆍ이소영, 2019, “우리나라 센서스 지리의 고도화를 위한 제언: 메조-스케일 공간단위의 다양화,” 지리교육논집, 63, 1–13. [I410-ECN-0102-2023-300-000520986](https://kiss.kstudy.com/Detail/Ar?key=3935188). [{{< bi file-pdf-fill >}}](papers/2019_03_지리교육논집_이상일_이소영.pdf)

-   이상일, 2019, “고유벡터공간필터링 접근법에 기반한 피어슨 상관계수의 요소분해,” 대한지리학회지, 54(5), 545–560. <https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002522013>. [{{< bi file-pdf-fill >}}](papers/2019_02_대한지리학회지_이상일.pdf)

-   Lee, Sang-Il, Monghyeon Lee, Yongwan Chun, and Daniel A. Griffith. 2019, “Uncertainty in the effects of the modifiable areal unit problem under different levels of spatial autocorrelation: A simulation study,” *International Journal of Geographical Information Science,* 33(6), 1135–1154. <https://doi.org/10.1080/13658816.2018.1542699>. [{{< bi file-pdf-fill >}}](papers/2019_01_IJGIS_Lee_Lee_Chun_Griffith.pdf)

### 2018

-   김민성ㆍ이상일, 2018, “대학생들의 방향과 위치에 대한 인지지도,” 한국지리학회지, 7(3), 245–259. <https://doi.org/10.25202/JAKG.7.3.1>. [{{< bi file-pdf-fill >}}](papers/2018_02_한국지리학회지_김민성_이상일.pdf)

-   이상일ㆍ조대헌ㆍ이민파, 2018, “피어슨 상관계수의 공간화: 세 관련 기법 간의 비교 실험 연구,” 대한지리학회지, 53(5), 761–776. <https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002403174>. [{{< bi file-pdf-fill >}}](papers/2018_01_대한지리학회지_이상일_조대헌_이민파.pdf)

### 2017

-   이상일ㆍ조대헌ㆍ이민파, 2017, “공간적 자기상관 통계량의 고유벡터 간 비교 연구: 공간근접성행렬의 효과와 공간적 회귀분석에의 함의를 중심으로,” 대한지리학회지, 52(5), 645–660. <https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002282407>. [{{< bi file-pdf-fill >}}](papers/2017_05_대한지리학회지_이상일_조대헌_이민파.pdf)

-   조대헌ㆍ이상일, 2017, “GIS 분석을 이용한 『대동여지도』의 투영법 추정,” 한국지도학회지, 17(2), 11–27. <https://doi.org/10.16879/jkca.2017.17.2.011>. [{{< bi file-pdf-fill >}}](papers/2017_04_한국지도학회지_조대헌_이상일.pdf)

-   Kim, Minsung, Daeheon Cho, Sang-II Lee, and Jungyeop Shin, 2017, “The development and applicability of a web-based time-geographic visualisation tool, ” *Geography*, 102(2), 71–78. <https://doi.org/10.1080/00167487.2017.12094012>. [{{< bi file-pdf-fill >}}](papers/2017_03_GEO_Kim_Cho_Lee_Shin.pdf)

-   Lee, Sang-Il, 2017, “Correlation and spatial autocorrelation, ” In Shashi Shekhar, Hui Xiong, and Xun Zhou, eds., *Encyclopedia of GIS*, Volume 1, 2nd edition, Cham: Springer International Publishing, 360–368. <https://doi.org/10.1007/978-3-319-17885-1_1524>. [{{< bi file-pdf-fill >}}](papers/2017_02_EGIS_Lee.pdf)

-   이상일ㆍ김민성, 2017, “지리정보시스템(GIS)과 지리교육 연구의 동향과 쟁점,” 대한민국학술원, 학문연구의 동향과 쟁점, 제6집(고고학ㆍ민속학ㆍ인문지리학ㆍ문화인류학), 대한민국학술원, 404–438. [{{< bi file-pdf-fill >}}](papers/2017_01_학술원_이상일_김민성.pdf)

### 2016

-   이상일, 2016, “한국의 신도시: 역사와 전망,”, 한국인구학회편, 인구대사전, 통계청, 844–848. [{{< bi file-pdf-fill >}}](papers/2016_07_인구대사전(한국의%20신도시%20역사와%20전망)_이상일.pdf)

-   정기원ㆍ이상일, 2016, “인구정책: 한국-인구분산정책,” 한국인구학회편, 인구대사전, 통계청, 567–570. [{{< bi file-pdf-fill >}}](papers/2016_06_인구대사전(한국%20인구분산정책)_정기원_이상일.pdf)

-   정기원ㆍ이상일, 2016, “인구정책: 분산정책,”, 한국인구학회편, 인구대사전, 통계청, 544–547. [{{< bi file-pdf-fill >}}](papers/2016_05_인구대사전(인구정책%20분산정책)_정기원_이상일.pdf)

-   이상일ㆍ조대헌ㆍ이민파, 2016, “일변량 공간연관성통계량에 대한 비교 연구 (II): 국지적 *S~i~* 통계량을 중심으로,” 한국지리학회지, 5(3), 375–396. [G704-SER000004171.2016.5.3.012](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002178247). [{{< bi file-pdf-fill >}}](papers/2016_04_한국지리학회지_이상일_조대헌_이민파.pdf)

-   김민성ㆍ이상일ㆍ이소영, 2016, “지리공간서비스의 교육적 함의와 교수학습 모델 개발,” *The SNU Journal of Education Research*, 25(1), 1–26. [G704-000009.2016.25.1.001](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002155068). [{{< bi file-pdf-fill >}}](papers/2016_03_SNU_김민성_이상일_이소영.pdf)

-   조대헌ㆍ이상일, 2016, “국제지도학회 제16회 총회 및 제27회 학술대회 참석 보고: 브라질 리우데자네이루,” 한국지도학회지, 16(1), 79–90. [{{< bi file-pdf-fill >}}](papers/2016_02_한국지도학회지_조대헌_이상일.pdf)

-   Lee, Sang-Il, 2016, “Spatial Statistics and Geostatistics: Theory and Applications for Geographic Information Science and Technology, by Yongwan Chun and Daniel A. Griffith, Thousand Oaks, CA, SAGE Publications, 2013, 181 Pp., \$47.70/£24.29 (Paperback), ISBN 978-1-446-20174-9,” *International Journal of Geographical Information Science*, 30(6), 1250–1253. <https://doi.org/10.1080/13658816.2015.1107074>. [{{< bi file-pdf-fill >}}](papers/2016_01_IJGIS_Lee.pdf)

### 2015

-   이상일ㆍ조대헌, 2015, “IMW의 지도학사적 의의와 유산,” 한국지도학회지, 15(3), 49–62. <https://doi.org/10.16879/jkca.2015.15.3.049>. [{{< bi file-pdf-fill >}}](papers/2015_03_한국지도학회지_이상일_조대헌.pdf)

-   조대헌ㆍ이상일ㆍ김진혁, 2015, “국가 지형도 도엽명 부여 원칙 설정 및 적용: 1: 50,000 지형도를 중심으로,” 한국지도학회지, 15(3), 23–38. <https://doi.org/10.16879/jkca.2015.15.3.023>. [{{< bi file-pdf-fill >}}](papers/2015_02_한국지도학회지_조대헌_이상일_김진혁.pdf)

-   이상일ㆍ조대헌ㆍ이민파, 2015, “일변량 공간연관성통계량에 대한 비교 연구 (I): 전역적 *S* 통계량을 중심으로,” 한국지리학회지, 4(2), 329–345. [G704-SER000004171.2015.4.2.008](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002065246). [{{< bi file-pdf-fill >}}](papers/2015_01_한국지리학회지_이상일_조대헌_이민파.pdf)

### 2014

-   이상일, 2014, “지도에서 인류의 미래 모습을 발견하다, ” 문화재사랑, 12월호(통권121호), 문화재청. 12–15. [{{< bi file-pdf-fill >}}](papers/2014_03_문화재사랑(문화재청)_이상일.pdf)

-   Lee, Sang-Il, 2014, “Spatial Mathematics: Theory and Practice Through Mapping by Sandra Lach Arlinghaus and Joseph J.Kerski. Boca Raton, FL: CRC Press, 2014, 300 Pp,” *Geographical Analysis*, 46(4), 456–458. <https://doi.org/10.1111/gean.12066>. [{{< bi file-pdf-fill >}}](papers/2014_02_GA_Lee.pdf)

-   이상일ㆍ조대헌, 2014, “고지도의 왜곡 양상에 대한 GIS-기반 연구: 대동여지도를 사례로 한 시론적 분석,” 대한지리학회지, 49(3), 438–455. [G704-000550.2014.49.3.010](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001893735). [{{< bi file-pdf-fill >}}](papers/2014_01_대한지리학회지_이상일_조대헌.pdf)

### 2013

-   이화정ㆍ이상일ㆍ조대헌, 2013, “거주지 이동을 통한 학교 선택의 공간성에 관한 연구: 서울시 초등학생의 전학 양상을 사례로 한 시론적 분석,” 대한지리학회지, 48(6), 897–913. [G704-000550.2013.48.6.006](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001835690). [{{< bi file-pdf-fill >}}](papers/2013_04_대한지리학회지_이화정_이상일_조대헌.pdf)

-   이상일ㆍ조대헌ㆍ구형모, 2013, “웹-기반 다국어 지명 서비스의 구현 방안 연구,” 한국지도학회지, 13(1), 33–46. [G704-SER000008969.2013.13.1.007](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001767919). [{{< bi file-pdf-fill >}}](papers/2013_03_한국지도학회지_이상일_조대헌_구형모.pdf)

-   조대헌ㆍ이상일ㆍ구형모, 2013, “다국어 세계지도의 제작 방안에 관한 연구,” 한국지도학회지, 13(1), 1–15. [G704-SER000008969.2013.13.1.005](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001767912). [{{< bi file-pdf-fill >}}](papers/2013_02_한국지도학회지_조대헌_이상일_구형모.pdf)

-   Kim, Minsung, Kamyoung Kim, and Sang-Il Lee, 2013, “Pedagogical potential of a web-based GIS application for migration data: A preliminary investigation in the context of South Korea,” *Journal of Geography*, 112(3), 97–107. <https://doi.org/10.1080/00221341.2012.709261>. [{{< bi file-pdf-fill >}}](papers/2013_01_JG_Kim_Kim_Lee.pdf)

### 2012

-   이상일, 2012, “우리나라 시도별 장래 가구 추계: 시론적 연구,” 지리교육논집, 56, 1–16. [I410-ECN-0102-2014-300-001629258](https://kiss.kstudy.com/Detail/Ar?key=3213773). [{{< bi file-pdf-fill >}}](papers/2012_13_지리교육논집_이상일.pdf)

-   이상일ㆍ조대헌, 2012, “대한민국 주변도 제작을 위한 최적의 지도 투영법 선정: GIS-기반 투영 왜곡 분석,” 한국지도학회지, 12(3), 1–16. [G704-SER000008969.2012.12.3.001](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001734586). [{{< bi file-pdf-fill >}}](papers/2012_12_한국지도학회지_이상일_조대헌.pdf)

-   이상일ㆍ김감영ㆍ제갈영, 2012, “지오컴퓨테이션 접근에 의한 주택시장지역의 설정: 우리나라 수도권에의 적용,” 한국도시지리학회지, 15(3), 59–75. [G704-001360.2012.15.3.002](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001725737). [{{< bi file-pdf-fill >}}](papers/2012_11_한국도시지리학회지_이상일_김감영_제갈영.pdf)

-   이상일ㆍ조대헌, 2012, “비선호 시설의 인구분포 관련 입지기준 평가를 위한 GIS-기반 방법론 연구: 원자력 발전소의 경우,” 대한지리학회지, 47(5), 755–774. [G704-000550.2012.47.5.002](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001710759). [{{< bi file-pdf-fill >}}](papers/2012_10_대한지리학회지_이상일_조대헌.pdf)

-   이상일, 2012, “공간적 상호작용론의 본질과 연구 영역: 인문지리학에 대한 통섭적 접근,” 한국지리학회지, 1(1), 137–151. [G704-SER000004171.2012.1.1.011](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002075758). [{{< bi file-pdf-fill >}}](papers/2012_09_한국지리학회지_이상일.pdf)

-   Lee, Sang-Il, and Kamyoung Kim, 2012, “Geospatial analysis and modeling in Korea: A literature review,” *Journal of the Korean Geographical Society*, 47(4), 606–624. [G704-000550.2012.47.4.007](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001692622). [{{< bi file-pdf-fill >}}](papers/2012_08_대한지리학회지_Lee_Kim.pdf)

-   Kim, Kamyoung, Sang-Il Lee, Jungyeop Shin, and Eunyoung Choi, 2012, “Developing a flow mapping module in a GIS environment,” *The Cartographic Journal*, 49(2), 164–175. <https://doi.org/10.1179/174327711X13166800242356>. [{{< bi file-pdf-fill >}}](papers/2012_07_CJ_Kim_Lee_Shin_Choi.pdf)

-   조대헌ㆍ정재준ㆍ이상일, 2012, “디지털 맵 데이터를 이용한 세계지도 제작의 실행 방안,” 한국지도학회지, 12(1), 33–47. [G704-SER000008969.2012.12.1.008](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001658820). [{{< bi file-pdf-fill >}}](papers/2012_06_한국지도학회지_조대헌_정재준_이상일.pdf)

-   이상일ㆍ조대헌ㆍ이건학, 2012, “태평양 중심의 세계지도 제작을 위한 최적의 지도 투영법 선정,” 한국지도학회지, 12(1), 1–20. [G704-SER000008969.2012.12.1.006](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001658808). [{{< bi file-pdf-fill >}}](papers/2012_05_한국지도학회지_이상일_조대헌_이건학.pdf)

-   김감영ㆍ이상일, 2012, “Web GIS 기반 유선도 작성을 통한 인구이동통계의 지리적 시각화,” 대한지리학회지, 47(2), 268–281. [G704-000550.2012.47.2.008](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001659817). [{{< bi file-pdf-fill >}}](papers/2012_04_대한지리학회지_김감영_이상일.pdf)

-   이상일ㆍ조대헌, 2012, “지역간 인구이동의 예측을 통한 우리나라 시도별 장래 인구 추계: 다지역 코호트-요인법의 적용,” 대한지리학회지, 47(1), 98–120. [G704-000550.2012.47.1.001](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001641302). [{{< bi file-pdf-fill >}}](papers/2012_03_대한지리학회지_이상일_조대헌.pdf)

-   김감영ㆍ신정엽ㆍ이상일, 2012, “에너지 산업에서 장기예보의 사회·경제적 가치 평가 방법론 고찰,” 기후연구, 7(1), 98–118. [G704-SER000001084.2012.7.1.001](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001641350). [{{< bi file-pdf-fill >}}](papers/2012_02_기후연구_김감영_신정엽_이상일.pdf)

-   Kim, Minsung, and Sang-Il Lee, 2012, “South Korea: GIS implementation profiles among secondary geography teachers,” In Andrew J. Milson, Ali Demirci, and Joseph J. Kerski, eds., *International Perspectives on Teaching and Learning with GIS in Secondary Schools*, Dordrecht: Springer Netherlands, 233–241.  <https://doi.org/10.1007/978-94-007-2120-3_26>. [{{< bi file-pdf-fill >}}](papers/2012_01_IPTLGISSS_Kim_Lee.pdf)

### 2011

-   조대헌ㆍ신정엽ㆍ이상일ㆍ정준석ㆍ김현경, 2011, “GIS-기반 장기 기상 예보 활용 시스템 개발: 에너지 산업을 사례로 한 프로토타입 시스템,” 한국지도학회지, 11(3), 89–104. [G704-SER000008969.2011.11.3.008](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001622064). [{{< bi file-pdf-fill >}}](papers/2011_03_한국지도학회지_조대헌_신정엽_이상일_정준석_김현경.pdf)

-   Kim, Min-Sung, Robert Bednarz, and Sang-Il Lee, 2011, “GIS education for teachers in South Korea: Who participates and why?,” *Journal of the Korean Geographical Society,* 46(3), 382–395. [G704-000550.2011.46.3.004](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001576076). [{{< bi file-pdf-fill >}}](papers/2011_02_대한지리학회지_Kim_Bednarz_Lee.pdf)

-   조대헌ㆍ이상일, 2011, “이지역 코호트-요인법을 이용한 부산광역시 장래 인구 추계,” 대한지리학회지, 46(2), 212–232. [G704-000550.2011.46.2.003](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001576066). [{{< bi file-pdf-fill >}}](papers/2011_01_대한지리학회지_조대헌_이상일.pdf)

### 2010

-   신정엽ㆍ이건학ㆍ이상일, 2010, “지도학적 원리에 기반한 국가지도도식규정의 효율적인 개선 및 유지발전 방안 수립 연구,” 한국지도학회지, 10(2), 59–77. [G704-SER000008969.2010.10.2.009](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001515917). [{{< bi file-pdf-fill >}}](papers/2010_02_한국지도학회지_신정엽_이건학_이상일.pdf)

-   이상일ㆍ조대헌ㆍ손학기ㆍ채미옥, 2010, “공간 클러스터의 범역 설정을 위한 GIS-기반 방법론 연구: 수정 AMOEBA 기법,” 대한지리학회지, 45(4), 502–520. [G704-000550.2010.45.4.002](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001474925). [{{< bi file-pdf-fill >}}](papers/2010_01_대한지리학회지_이상일_조대헌_손학기_채미옥.pdf)

### 2009

-   신정엽ㆍ이상일ㆍ김감영ㆍ최은영, 2009, “Web GIS를 기반으로 한 효율적인 인구이동 통계 제공 방안 수립 연구,” 한국지도학회지, 9(2), 59–71. [G704-SER000008969.2009.9.2.005](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001404745). [{{< bi file-pdf-fill >}}](papers/2009_03_한국지도학회지_신정엽_이상일_김감영_최은영.pdf)

-   Lee, Sang-Il, 2009, “Neighborhood effects,” In Rob Kitchin and Nigel Thrift, eds., *International Encyclopedia of Human Geography*, Vol.7, Oxford: Elsevier, 349–353. <https://doi.org/10.1016/B978-008044910-4.00480-6>. [{{< bi file-pdf-fill >}}](papers/2009_02_IEHG_Lee.pdf)

-   Lee, Sang-Il. 2009, “A generalized randomization approach to local measures of spatial association,” *Geographical Analysis,* 41(2), 221–248. <https://doi.org/10.1111/j.1538-4632.2009.00749.x>. [{{< bi file-pdf-fill >}}](papers/2009_01_GA_Lee.pdf)

### 2008

-   이상일ㆍ신정엽ㆍ김감영ㆍ최은영, 2008, “웹-기반 인구이동 데이터 제공 방식의 국제 비교,” 지리교육논집, 52, 1–24. [I410-ECN-0102-2012-370-002870528](https://kiss.kstudy.com/Detail/Ar?key=2980750). [{{< bi file-pdf-fill >}}](papers/2008_03_지리교육논집_이상일_신정엽_김감영_최은영.pdf)

-   Lee, Sang-Il, 2008, “A generalized procedure to extract higher order moments of univariate spatial association measures for statistical testing under the normality assumption,” *Journal of the Korean Geographical Society,* 43(2), 253–262. [G704-000550.2008.43.2.002](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001261194). [{{< bi file-pdf-fill >}}](papers/2008_02_대한지리학회지_Lee.pdf)

-   이상일, 2008, “거주지 분화에 대한 공간통계학적 접근 (II): 국지적 공간 분리성 측도를 이용한 탐색적 공간데이터 분석,” 대한지리학회지, 43(1), 134–153. [G704-000550.2008.43.1.009](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001246414). [{{< bi file-pdf-fill >}}](papers/2008_01_대한지리학회지_이상일.pdf)

### 2007

-   이상일ㆍ김감영, 2007, “GIS-기반 대시메트릭 매핑(dasymetric mapping) 기법을 이용한 서울시 인구밀도 분포의 재현,” 한국지도학회지, 7(2), 53–67. <https://www.earticle.net/Article/A114034>. [{{< bi file-pdf-fill >}}](papers/2007_02_한국지도학회지_이상일_김감영.pdf)

-   이상일, 2007, “거주지 분화에 대한 공간통계학적 접근 (I): 공간 분리성 측도의 개발, ” 대한지리학회지, 42(4), 616–631. [G704-000550.2007.42.4.006](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001084989). [{{< bi file-pdf-fill >}}](papers/2007_01_대한지리학회지_이상일.pdf)

### 2006

-   이상일, 2006, “고용 변동에 따른 인구 규모와 산업 구조 상의 장기적 변화 추정: 2020년 서울을 사례로,” 지리교육논집, 50, 27–39. [I410-ECN-0102-2009-370-000118755](https://kiss.kstudy.com/Detail/Ar?key=2606369){.uri}. [{{< bi file-pdf-fill >}}](papers/2006_02_지리교육논집_이상일.pdf)

-   이상일, 2006, “메이포 콴(mei-Po Kwan): 시간지리학 연구에 있어서 GIS 방법론(대담),” 국토, 7월호, 국토연구원, 85–95. [{{< bi file-pdf-fill >}}](papers/2006_01_국토(국토연구원)_이상일.pdf)

### 2005

-   이기석ㆍ최재헌ㆍ이상일, 2005, “지리적 특성,” 국토지리정보원, 한국지리지: 경상편, 국토지리정보원, 23-34. [{{< bi file-pdf-fill >}}](papers/2005_03_한국지리지(경상편)_이기석_최재헌_이상일.pdf)

-   Lee, Sang-Il, 2005, “Between the quantitative and GIS revolutions: Towards an SDA-centered GIScience,” *Journal of Geography Education*, 49, 268–284. [I410-ECN-0102-2012-370-002870528](https://kiss.kstudy.com/Detail/Ar?key=2581654). [{{< bi file-pdf-fill >}}](papers/2005_02_지리교육논집_Lee.pdf)

-   Brown, Lawrence A., Sang-Il Lee, Linda Lobao, and Su-Yeul Chung, 2005, “Continuity amidst restructuring: The U.S. gender division of labor in geographic perspective, 1970 and 1990,” *International Regional Science Review,* 28(3), 271–301, <https://doi.org/10.1177/0160017604268789>. [{{< bi file-pdf-fill >}}](papers/2005_01_IRSR_Brown_Lee_Lobao_Chung.pdf)

### 2004

-   Lee, Sang-Il, 2004, “A generalized significance testing method for global measures of spatial association: An extension of the Mantel test,” *Environment and Planning A: Economy and Space*, 36(9), 1687–1703. <https://doi.org/10.1068/a34143>. [{{< bi file-pdf-fill >}}](papers/2004_03_EPA_Lee.pdf)

-   Lee, Sang-Il, 2004. “Spatial data analysis for the U.S. regional income convergence, 1969-1999: A critical appraisal of β-convergence,” *Journal of the Korean Geographical Society,* 39(2), 212–228. [G704-000550.2004.39.2.005](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART000929820). [{{< bi file-pdf-fill >}}](papers/2004_02_대한지리학회지_Lee.pdf)

-   Lee, Sang-Il, 2004, “Exploratory spatial data analysis of σ-convergence in the U.S. regional income distribution, 1969-1999,” *Journal of the Korean Urban Geographical Society,* 7(1), 79–95. [G704-001360.2004.7.1.004](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART000936518). [{{< bi file-pdf-fill >}}](papers/2004_01_한국도시지리학회지_Lee.pdf)

### 2003

-   이상일, 2003, “GIS를 이용한 2000년 강원도 인구 분포의 시각화에 관한 연구,” 강원지리, 20, 24–47. [{{< bi file-pdf-fill >}}](papers/2003_01_강원지리_이상일.pdf)

### 2001

-   Lee, Sang-Il, 2001, “Developing a bivariate spatial association measure: An integration of Pearson’s *r* and Moran’s *I*,” *Journal of Geographical Systems,* 3(4), 369–385. <https://doi.org/10.1007/s101090100064>. [{{< bi file-pdf-fill >}}](papers/2001_02_JGS_Lee.pdf)

-   Lee, Sang-Il, 2001, “A spatial statistical approach to migration studies: Exploring the spatial heterogeneity in place-specific distance parameters,” *Journal of the Korean Association of Regional Geographers,* 7(3), 107–120. <https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE02494458>. [{{< bi file-pdf-fill >}}](papers/2001_01_한국지역지리학회지_이상일.pdf)

### 1999

-   이상일, 1999, “기능지역의 설정과 ‘공간단위 수정가능성의 문제 (MAUP)’,” 한국지리환경교육학회지, 7(2), 757–783. <https://kiss.kstudy.com/Detail/Ar?key=1822932>. [{{< bi file-pdf-fill >}}](papers/1999_01_지리환경교육_이상일.pdf)

### 1990–1995

-   이상일, 1995, “삐에르 부르디외의 사회지리학: 문화와 소비의 사회지리학을 지향하며,” 응용지리, 18, 57–101. <https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE02115592>. [{{< bi file-pdf-fill >}}](papers/1995_01_응용지리_이상일.pdf)

-   이상일, 1993, “포스트모더니즘과 지리학: 지리학의 해체인가 재구성인가?,” 지리교육논집, 30, 51–79. [I410-ECN-0102-2009-370-008160844](https://kiss.kstudy.com/Detail/Ar?key=410352). [{{< bi file-pdf-fill >}}](papers/1993_01_지리교육논집_이상일.pdf)

-   이상일, 1990, “실재론의 지리학적 함의와 공간의 상대적 자율성에 관한 연구,” 지리교육논집, 24, 1–24. [I410-ECN-0102-2009-370-008161265](https://kiss.kstudy.com/Detail/Ar?key=410310). [{{< bi file-pdf-fill >}}](papers/1990_01_지리교육논집_이상일.pdf)
