---
title: "Spring/2024 Designing Human and Social Education Contents for AI Convergence Education"
subtitle: "AI 융합교육을 위한 인문사회 컨텐츠 설계"
title-block-banner: ../images/banner_ai_edu.jpg
author: "Sang-Il Lee"
date-modified: last-modified
number-sections: false
bibliography: references.bib
---

## Main Focus

-   This course focuses on how technological advances associated with data science and artificial intelligence could enhance social studies education.

-   Students are expected:

    -   to understand possibilities and limitations of those technologies for social studies education,

    -   to develop their abilities to design teaching-learning contents by fusing the technologies and particular subject matters, and

    -   to get to possess an introductory level of computer programming for the technologies.

<br>

## Class Setting

### LMS (Learning Management System)

-   eTL at Seoul National University ([SNU eTL](http://etl.snu.ac.kr/))

-   Lecture notes, materials, references, and etc.

### Class Design

-   Classes are conducted in a combination of lecture and lab exercise.

-   Lecure contents are composed of 8 topics: Concepts and Principles of Data Science, Data Science and Education, Population Topics for Contents Development, Data Collection by Webscraping, Analysis of Unstructured Data (Text Mining), Data Exploration and Visualization, Artificial Intelligence and Machine Learning, Development of Web Applications.

-   Each lecture is accompanied by an R excercise.

-   During the final two weeks, each student is expected to give a presentation about designing social studies class contents for AI-Integrated education.

<br>

## Student Responsibilities

### Presentation

-   Each student should give a presentation on designing social studies class contents for AI-Integrated education.

    -   Subject: one or two population Issues (low birth rate, aging, population cliff, regional extinction, school-age population)

    -   Data: KOSIS or World Population Prospects 2022

    -   Form: 20-minute-long powerpoint presentation

### Term Paper

-   Each student should submit a term paper about the presentation above at the end of the semester.

<br>

## Grading Method

### Attendance (15%)

-   Penalty will be given for each absence/lateness.

### Presentation (35%)

-   Overall performance will be evaluated.

### Term Paper (50%)

-   The format of the term paper can be freely chosen.
-   Due date: 6/18/2024 (Thuesday)

<br>

## References

### Data Science

-   Wickham, Hadley, Mine Çetinkaya-Rundel, and Garrett Grolemund, 2023, [*R for Data Science: Import, Tidy, Transform, Visualize, and Model Data*](https://r4ds.hadley.nz/)*,* 2nd edition, Boston: O’Reilly. (김설기ㆍ최혜민 옮김, 2019, [R을 활용한 데이터 과학: 데이터 불러오기, 정리하기, 변형하기, 시각화하기, 모델링하기](https://www.yes24.com/Product/Goods/67856488), 1판, 서울: 인사이트.)
-   차영준ㆍ박진표, 2022, [데이터과학 입문을 위한 R과 타이디버스](https://www.yes24.com/Product/Goods/111420341), 파주: 자유아카데미.
-   양윤석ㆍ오일석ㆍ강래형, 2019, [R로 배우는 데이터 과학: 분석에서 예측을 위한 모델링까지](https://www.yes24.com/Product/Goods/73049003), 서울: 한빛아카데미.

### Data Visualization

-   Kabacoff, Robert, 2024, [*Modern Data Visualization with R*](https://rkabacoff.github.io/datavis/index.html), Boca Raton: CRC Press.

-   Dougherty, Jack, and Ilya Ilyankou, 2021, [*Hands-on Data Visualization: Interactive Storytelling from Spreadsheets to Code*](https://handsondataviz.org/), Boston: O’Reilly. (김태헌 옮김, 2022, [핸즈온 데이터 시각화: 효과적인 데이터 시각화 전략부터 20가지 시각화 도구 사용법까지](https://www.yes24.com/Product/Goods/110225484), 한빛미디어)

-   Wilke, C., 2019, [*Fundamentals of Data Visualization: A Primer on Making Informative and Compelling Figures*](https://clauswilke.com/dataviz/), Sebastopol, CA: O’Reilly. (권혜정, 2020, [데이터 시각화 교과서: 데이터 분석의 본질을 살리는 그래프와 차트 제작의 기본 원리와 응용](https://www.yes24.com/Product/Goods/87631760), 의왕: 책만.)

### Statistical Foundation

-   Bruce, Peter C., Andrew Bruce, and Peter Gedeck, 2020, [*Practical Statistics for Data Scientists: 50+ Essential Concepts Using R and Python*](https://www.amazon.com/Practical-Statistics-Data-Scientists-Essential/dp/149207294X/ref=sr_1_1?crid=98UZEABX2F4Q&dib=eyJ2IjoiMSJ9.F4tO6GMw72DFF7NQRdwBqEC0yTH5VyuO-miwDjnFTNNLSKmqumN48VZFUwWeUH0ZKSyXucoF7sIL-okC6RXJToNl542GnCLV8tS5OlrQtsC7Rugp1EyMYEaTuTW_8gAgJ7SK_kYPuHHydz8XI11WmcNjN_2CUigbo2cfwqIMXD6oY8AwVg2fwkvn__e2Yk1CsPQyGQot0RJRezwz4GlKBgQMe83M9dJ18dua-luUl2k.Dg0hpdMezDfpXwGPn9nIwPAz7WNs5uGwh2lPtgsoWKs&dib_tag=se&keywords=practical+statistics+for+data+scientists&qid=1705832562&s=books&sprefix=practical+statistics+for+data+scientist%2Cstripbooks-intl-ship%2C261&sr=1-1)*,* Second edition, Sebastopol, CA: O’Reilly. (이준용 옮김, 2021, [데이터 과학을 위한 통계](https://www.yes24.com/Product/Goods/99942893), 서울: 한빛미디어.)

-   오진호, 2022, [기초통계학과 데이터 사이언스: R 활용](https://www.yes24.com/Product/Goods/112198610), 파주: 자유아카데미.

### Web Scraping

-   곽기영, 2022, [R을 이용한 웹스크레이핑과 데이터분석](https://www.yes24.com/Product/Goods/109005331), 서울: 청람.

### Text Analysis

-   Hvitfeldt, Emil, and Julia Sigle, 2022, [*Supervised Machine Learning for Text Analysis in R*](https://smltar.com/)*,* Boca Raton: CRC Press.

-   한국R사용자회ㆍ안도현, 2022, [R 텍스트마이닝](https://r2bit.com/book_tm/index.html), 오픈전자책.

-   김영우, 2021, [쉽게 배우는 R 텍스트 마이닝](https://www.yes24.com/Product/Goods/43868089), 서울: 이지스퍼블리싱.

-   백영민, 2020, [R을 이용한 텍스트 마이닝](https://www.yes24.com/Product/Goods/89484023), 파주: 한울엠플러스.

### Web Application Development

-   Granjon, David, 2022, [*Outstanding User Interfaces with Shiny*](https://unleash-shiny.rinterface.com/), Boaca Raton: CRC Press.

-   Fay, Colin, Vincent Guyader, Sebastien Rochette, and Cervan Girard. 2022, [*Engineering Production-Grade Shiny Apps*](https://engineering-shiny.org/index.html), Boca Raton: CRC Press.

-   Wickham, Hadley, 2021, [*Mastering Shiny: Build Interactive Apps, Reports, and Dashboards Power by R*](https://mastering-shiny.org/)*,* Sebastopol, CA: O’REILLY. (이영록 옮김, 2022, [R 사용자를 위한 Shiny 마스터 가이드](https://www.yes24.com/Product/Goods/116598818), 서울: 인사이트.)

### Machine Learning and Deep Learning

-   Lantz, Brett, 2023, [*Machine Learning with R: Learn Techniques for Building and Improving Machine Learning Models, from Data Preparation to Model Tuning, Evaluation, and Working with Big Data*](https://www.amazon.com/Machine-Learning-cleansing-modeling-tidyverse/dp/1801071322/ref=sr_1_1?crid=9EPNBAD4F79U&dib=eyJ2IjoiMSJ9.8yFZK-uRw9ooLv6ZlfzgpK3TUC0TV7WSoYOOrAlOKJzz2j5Rs5LJAPgG59PT_Qz9a-KPQdKlm62KboAkquQ8KSsdRQm_3Dv5LBHP4pQIfSqrG4H8jA-9bgys05ZCoUPEo-yTlRW4NZCeuTDo5Pdsl8hSZj7tWrBb3il1RSuRjkl4s0Y5P0i0EJJ2FNteKnqJY4C7qAAxF6gRWuxSeTlYWVRXUmpnThP-l6_qodjcN64.8apIBHXT0OxdRDm6B3MFF_Yi1cooPbDLw6mdwn7DGaw&dib_tag=se&keywords=Machine+Learning+with+R&qid=1705835635&s=books&sprefix=machine+learning+with+r%2Cstripbooks-intl-ship%2C496&sr=1-1)*,* Fourth edition, Birmingham Mumbai: Packt. (이병욱, 2024, [R을 활용한 머신 러닝](https://www.yes24.com/Product/Goods/124503175), 4판, 서울: 에이콘출판사.

-   Chollet, François, Tomasz Kalinowski, and J. J. Allaire, 2022, [*Deep Learning with R*](https://www.amazon.com/Deep-Learning-Second-Francois-Chollet-dp-1633439844/dp/1633439844/ref=dp_ob_title_bk)*,* Second edition, Shelter Island, NY: Manning. (박진수 옮김, 2019, [케라스 창시자의 딥러닝 with R](https://www.yes24.com/Product/Goods/69608911), 1판, 파주: 제이펍.)

-   Lesmeister, Cory, 2019, [*Mastering Machine Learning with R: Advanced Machine Learning Techniques for Building Smart Applications with R*](https://www.amazon.com/Mastering-Machine-Learning-techniques-applications/dp/1789618002/ref=sr_1_1?crid=2IG8XWOEJLPHR&dib=eyJ2IjoiMSJ9.LkUWBYaK8rUu26p3tqnrOrKknj51fcbFzRHMGo_uK_QcNm8806i2_50p-CkPRvJz8S7UjWVgGHvHS6vhnv7qDxwTinJSVXVArDPyduDkSxdvApNDdv7itBDgkGOGqhlHO4XiE9QzqtbhA0o-OinNlWQX2wRHdhE4SquUxeDD_wWBbrDNn50EuJUZvSAThxW7xlMQQfTkPmXfKQ1_h8Ig2ej0UHRzdLnlEzoaNdWx7CM.24LKDFK1y4kn_DUf9d4jUEqv_SyCtwhmD_zBC5hoGHk&dib_tag=se&keywords=mastering+machine+learning+with+r&qid=1705834894&s=books&sprefix=mastering+machine+learning+with+%2Cstripbooks-intl-ship%2C268&sr=1-1)*,* Third edition, Birmingham, UK: Packt Publishing. (김종원ㆍ김태영ㆍ류성희ㆍ이호. 2018, [R로 마스터하는 머신 러닝: 업무에 활용할 수 있는 선형모델에서 딥러닝까지](https://www.yes24.com/Product/Goods/59017119), 2판, 서울: 에이콘.)

-   장용식ㆍ최진호, 2020, [머신러닝을 활용한 R 데이터 분석](https://www.yes24.com/Product/Goods/89605827), 파주: 생능출판.

### Introduction to R

-   곽기영, 2022, [R 기초와 활용](https://www.yes24.com/Product/Goods/108044525), 서울: 청람.

-   강전희ㆍ엄동란, 2018, [처음 시작하는 R 데이터 분석](https://www.yes24.com/Product/Goods/64497252), 서울: 한빛미디어.

-   김영우, 2017, [쉽게 배우는 R 데이터 분석](https://www.yes24.com/Product/Goods/43868089), 서울: 이지스퍼블리싱.

<br>

## Calendar

| Week | Date | Content                                                |
|:----:|:----:|--------------------------------------------------------|
|  1   | 3/5  | Orientation                                            |
|  2   | 3/12 | Concepts and Principles of Data Science                |
|  3   | 3/19 | Data Science and Education                             |
|  4   | 3/26 | Population Topics for Contents Development 1           |
|  5   | 4/2  | Population Topics for Contents Development 2           |
|  6   | 4/9  | Data Collection by Web Scraping                        |
|  7   | 4/16 | Analysis of Unstructured Data: Text Mining             |
|  8   | 4/23 | Data Exploration and Visualization 1                   |
|  9   | 4/30 | Data Exploration and Visualization 2                   |
|  10  | 5/7  | Data Exploration and Visualization 3                   |
|  11  | 5/14 | Artificial Intelligence and Machine Learning 1         |
|  12  | 5/21 | Artificial Intelligence and Machine Learning 2         |
|  13  | 5/28 | Development of Web Applications                        |
|  14  | 6/4  | Designing Class Contents for AI-Integrated Education 1 |
|  15  | 6/11 | Designing Class Contents for AI-Integrated Education 2 |
